# Copyright (c) 2021 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Test Workflow

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/test-workflow.yml"
      - "config/example-sacCer3.config"
      - "main.nf"
      - "nextflow.config"
  pull_request:
    paths:
      - ".github/workflows/test-workflow.yml"
      - "config/example-sacCer3.config"
      - "main.nf"
      - "nextflow.config"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        NXF_VER: [ "22.10" ] #, "latest" ]

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: ${{ matrix.NXF_VER }}

      # TODO: remove this step once repo and package are public
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Nextflow
        env:
          NXF_ANSI_LOG: false
        run: |
          nextflow run -c config/example-sacCer3.config main.nf -with-docker

      - name: Compare checksum
        run: |
          checksum='3999bfea9a06a609ae39993f45b6e95933777a7ce8081c4a477f0932bf2b966c'
          fp='results/gene-annotations-sacCer3.db'
          
          shasum -c <(echo "$checksum  $fp")